using System.ComponentModel.DataAnnotations;

namespace BaseProject.Data.Enums
{
    public enum Provinces
    {
        [Display(Name = "An Giang")]
        AnGiang=0,
        [Display(Name = "Bà Rịa - Vũng Tàu")]
        BaRia_VungTau=1,
        [Display(Name = "Bắc Giang")]
        BacGiang=2,
        [Display(Name = "Bắc Kạn")]
        BacKan=3,
        [Display(Name = "Bạc Liêu")]
        BacLieu=4,
        [Display(Name = "Bắc Ninh")]
        BacNinh=5,
        [Display(Name = "Bến Tre")]
        BenTre=6,
        [Display(Name = "Bình Định")]
        BinhDinh=7,
        [Display(Name = "Bình Dương")]
        BinhDuong = 8,
        [Display(Name = "Bình Phước")]
        BinhPhuoc=9,
        [Display(Name = "Bình Thuận")]
        BinhThuan=10,
        [Display(Name = "Cà Mau")]
        CaMau=11,
        [Display(Name = "Cần Thơ")]
        CanTho=12,
        [Display(Name = "Cao Bằng")]
        CaoBang=13,
        [Display(Name = "Đà Nẵng")]
        DaNang=14,
        [Display(Name = "Đắk Lắk")]
        DakLak=15,
        [Display(Name = "Đắk Nông")]
        DakNong=16,
        [Display(Name = "Điện Biên")]
        DienBien=17,
        [Display(Name = "Đồng Nai")]
        DongNai=18,
        [Display(Name = "Đồng Tháp")]
        DongThap=19,
        [Display(Name = "Gia Lai")]
        GiaLai=20,
        [Display(Name = "Hà Nam")]
        HaNam=21,
        [Display(Name = "Hà Giang")]
        HaGiang=22,
        [Display(Name = "Hà Nội")]
        HaNoi=23,
        [Display(Name = "Hà Tĩnh")]
        HaTinh=24,
        [Display(Name = "Hải Phòng")]
        HaiPhong=25,
        [Display(Name = "Hải Dương")]
        HaiDuong=26,
        [Display(Name = "Hậu Giang")]
        HauGiang=27,
        [Display(Name = "Hòa Bình")]
        HoaBinh=28,
        [Display(Name = "Hưng Yên")]
        HungYen=29,
        [Display(Name = "Khánh Hóa")]
        KhanhHoa=30,
        [Display(Name = "Kiên Giang")]
        KienGiang=31,
        [Display(Name = "Kon Tum")]
        KonTum=32,
        [Display(Name = "Lai Châu")]
        LaiChau=33,
        [Display(Name = "Lâm Đồng")]
        LamDong=34,
        [Display(Name = "Lạng Sơn")]
        LangSon=35,
        [Display(Name = "Lào Cai")]
        LaoCai=36,
        [Display(Name = "Long An")]
        LongAn=37,
        [Display(Name = "Nam Định")]
        NamDinh=38,
        [Display(Name = "Nghệ An")]
        NgheAn=39,
        [Display(Name = "Ninh Bình")]
        NinhBinh=40,
        [Display(Name = "Ninh Thuận")]
        NinhThuan=41,
        [Display(Name = "Phú Thọ")]
        PhuTho=42,
        [Display(Name = "Phú Yên")]
        PhuYen=43,
        [Display(Name = "Quảng Bình")]
        QuangBinh=44,
        [Display(Name = "Quảng Nam")]
        QuangNam=45,
        [Display(Name = "Quảng Ngãi")]
        QuangNgai=46,
        [Display(Name = "Quảng Ninh")]
        QuangNinh=47,
        [Display(Name = "Quảng Trị")]
        QuangTri=48,
        [Display(Name = "Sóc Trăng")]
        SocTrang=49,
        [Display(Name = "Sơn La")]
        SonLa=50,
        [Display(Name = "Tây Ninh")]
        TayNinh=51,
        [Display(Name = "Thái Bình")]
        ThaiBinh=52,
        [Display(Name = "Thái Nguyên")]
        ThaiNguyen=53,
        [Display(Name = "Thanh Hóa")]
        ThanhHoa=54,
        [Display(Name = "Thừa Thiên Huế")]
        ThuaThienHue=55,
        [Display(Name = "Tiền Giang")]
        TienGiang=56,
        [Display(Name = "Hồ Chí Minh")]
        HoChiMinh=57,
        [Display(Name = "Trà Vinh")]
        TraVinh=58,
        [Display(Name = "Tuyên Quang")]
        TuyenQuang=59,
        [Display(Name = "Vĩnh Long")]
        VinhLong=60,
        [Display(Name = "Vĩnh Phúc")]
        VinhPhuc=61,
        [Display(Name = "Yên Bái")]
        YenBai=62
    }
}
